import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from sales_app.models import ProductMaster

product_names = [
    "SAPAMINE FDC", "AVITERA BLUE SE", "AVITERA GOLD SE", "AVITERA RED SE",
    "CERANINE SWPI LIQ", "ULTRAPHOR ETB IN. LIQ", "LYOPRINT RT-SA NEW",
    "CYCLANON XC-WI LIQ", "IMEROL XN.IN LIQ", "INVAZYME CAT-I",
    "DRIMAREN BLACK S CLASSIC", "SAPAMINE OC", "ERIOPON OS",
    "LUFIBROL 2 UD. IN", "PRESTOGEN FCB.IN LIQ", "RONGALIT ST LIQ",
    "IMACOL X-JET LIQ", "NOVACRON ATLANTIC EC-NC", "NOVACRON BLUE C-D",
    "NOVACRON MARIGOLD C-NC", "TERASIL SUPER BLACK W-01", "NOVACRON RED EC - 4B",
    "SOLIDOKOLL DPR.ID", "DRIMAREN NAVY R CLASSIC", "DRIMAREN RED 5B CLASSIC",
    "INVAZYME ADC", "ULTRATEX HES", "HELIZARIN 2016.IN", "IMEROL LF NEW LIQ.",
    "IMEROL TWI LIQ", "LYOPRINT RT-7 LIQ", "NOVACRON BOLD RED",
    "ALBATEX DBC", "CLARITE ONE", "CERALUBE HD.IN", "DRIMAREN BLACK SD CLASSIC",
    "DRIMAREN YELLOW 2R CLASSIC", "NOVACRON BOLD NAVY", "SOLUSOFT KNT",
    "DRIMAREN ULTIMATE BLUE HD", "DESTOFIL YL LIQ", "THERMACOL MIN",
    "ULTRAVON RW", "PRINTOFIX WHITE STR PA", "UVITEX SI LIQ-I",
    "PRIMASOL NF NEW LIQ.", "ARKOFIL UCF-4 GR", "LYOPRINT RT - PLUS",
    "APPRETAN MBX PREMIUM LIQ", "PHOBOL EXTENDER SFB", "PHOBOTEX CWR-ACE",
    "PHOBOTEX RSY", "ZELAN R3", "CLARITE 3X", "DILATIN ENI.IN LIQ",
    "INVATEX ED", "LYOPRINT PT- RV-I", "LYOPRINT RG GR", "ULTRAVON ECP",
    "ARKOFIL DEN", "ARKOFIL UCF6 P", "NOVACRON BR.TURQ EC-GN", "SAPAMINE LUB",
    "ALBAFLOW CIR-01", "AVITERA BLACK SE", "AVITERA DEEP SEA SE",
    "AVITERA ORANGE SE", "CLARITE G-I", "ERIOPON E3-SAVE", "LANASOL BLUE 3R",
    "LANASYN BLACK SD-L 170", "LANASYN NAVY SD-NLI", "LYOCOL RDNI LIQ",
    "NOVACRON BLACK NN", "NOVACRON PRUSSIAN BLUE W-B", "SETAMOL WS NEW",
    "TERASIL BLUE BGE 200%", "ULTRAVON EL", "INVATEX SW CONC",
    "ALBATEX AB-45", "ALBATEX RI", "DRIMAREN ULTIMATE RUBINE HD",
    "NOVACRON BLUE ECGC", "UVITEX BHA LIQ", "NOVACRON ORANGE EC-RN",
    "NOVACRON RED EC-3B", "INVAZYME FD-HL", "LEOMIN AFK.IN LIQ",
    "AVITERA CARDINAL SE", "AVITERA MAGENTA SE", "FUMEXOL WDN",
    "ALBATEX ONE", "LANASET NAVY R XN", "NYLOSAN RED N-RSI",
    "UVITEX BHT LIQ 115%", "ERIONAL FRN", "LANASET RED G GR",
    "LANASET YELLOW 2R GR", "PHOBOTEX NTR-50 LIQ", "LUMACRON BLACK SE",
    "FORON RUBINE S-9053", "SODYECRON YELLOW-BROWN S-IN", "TERASIL NAVY GRL- C 200%",
    "NOVACRON YELLOW EC-RG", "NOVACRON NAVY EC-BN", "PRINTOFIX WHITE FB-S ECO PA",
    "HELIZARIN ET LIQ", "LUPRINTOL FIXING AGENT FF.IN L", "LUPRINTOL SOFT VSN LIQ",
    "LUTEXAL ECO LIQ", "PRINTOFIX BLACK F-HDT HP", "PRINTOFIX BLUE FB-BT HP",
    "PRINTOFIX GOLDEN YELLOW FB-RM", "PRINTOFIX ORANGE FB-G HP", "PRINTOFIX RED FB-BG",
    "KIERALON DTC.IN", "MERCEROL RWLF LIQ", "ERIOPON R LIQ.",
    "ULTRATEX FLUID", "DRIMAREN RED CL BL", "NOVACRON BRILL. BLUE EC-B",
    "DICRYLAN AC-01", "LYOPRINT HV-RT", "EGANAL PS LIQ",
    "LUPRINTOL ANTIFOAM TC NEW LIQ", "PRINTOFIX WHITE FB-T PA",
    "ERIONYL RED A-3BN-01", "UVITEX BHA LIQ.", "ALBEGAL SET"
]

added_count = 0
for name in product_names:
    obj, created = ProductMaster.objects.get_or_create(
        material_name=name,
        defaults={'material_code': name}
    )
    if created:
        added_count += 1

print(f"Finished! Added {added_count} new products to Product Master.")
