import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from sales_app.models import ProductMaster

product_names = [
    "ALBAFIX ECO", "ALBAFLUID C", "ALBATEX AD", "ARKOFIL DNT P", "AVITERA BRIL. YELLOW SE",
    "AVITERA DEEP BLUE SE", "AVITERA LIGHT BLUE SE", "AVITERA LIGHT RED SE", "AVITERA YELLOW SE",
    "DEKOL FB-SN LIQ", "ERIOPON R", "INVADINE PBN", "INVATEX AC", "KNITTEX FFRC", "LYOPRINT AP",
    "NOVACRON BLACK W-NN", "NOVACRON SCARLET EC-6G", "NOVACRON BLUE C-5X", "NOVACRON BLUE EC-R",
    "NOVACRON BOLD YELLOW", "NOVACRON BR. TURQ. EC-GN", "NOVACRON DEEP BLUE S-DC",
    "NOVACRON DEEP NIGHT S-R", "NOVACRON DEEP RED EC-D", "NOVACRON NAVY W-B", "NOVACRON NAVY S-GI",
    "NOVACRON OCEAN S-R", "NOVACRON OLIVE EC-NC", "NOVACRON ORANGE EC-3R", "NOVACRON RED EC-2BL",
    "NOVACRON RED W-IN", "NOVACRON RUBY S-3B", "NOVACRON SUPER BLACK G", "NOVACRON YELLOW S-3R",
    "PRIMASOL AMK", "PRIMASOL NF NEW", "SAPAMINE CSN", "SETAMOL WS NEW P", "ULTRATEX TTK",
    "IMACOL MPE LIQ", "ULTRATEX SYN J CAN", "NUVA N1802", "ERIONAL PCL", "REVATOL NS LIQ",
    "TERATOP RED HL", "TERATOP YELL. HL-G 01 150%", "CERALUBE HD.IN LIQ", "DRIMAREN RED 5B",
    "KIERALON MRN LIQ", "LUFIBROL 2UD IN LIQ", "PRESTOGEN FCB. IN LIQ", "ULTRATEX STS-U",
    "TURPEX ACN NEW-I", "ERIONYL BLACK AMR", "INVADINE DA -02", "ULTRAPHIL PA", "PHOBOL EXTENDER XAN",
    "ALBATEX AR", "ALBAFIX WFF", "DRIMAREN BLACK N CLASSIC P", "ANTIMUSSOL SDF LIQ",
    "EGANAL DFT IN", "INVADINE MR-I", "LUFIBROL N LIQ", "ULTRATEX SI", "UV FAST W LIQ",
    "FORNAX W", "LANASET BORDEAUX B", "MIRALAN LTD", "TERASIL YELLOW W-6GS",
    "TERASIL RED W-4BS-01 150%", "TERASIL BLUE W-BLS", "UVITEX 4BB-I", "ALBATEX AB-55",
    "NYLOSAN YELLOW N-4GL", "UVITEX NFW-IN 450%", "ULTRAPHOR WHITENER INI", "LYOPRINT RD-HT-02",
    "PRINTOGEN INKJET DPE LIQ", "LEOMIN SWPI", "UVITEX BB-I", "TERATOP BLUE HL-GR",
    "LANASET GREY G-GR", "ARKOFIL MYC", "TERATOP BLACK HL-NF", "BACTOSOL PHC LIQ",
    "DICRYLAN SD", "FORON BLACK SE-RD 400", "BACTOSOL HP LIQ", "KIERALON FB-OLS NEW LIQ",
    "TREFIX FB AW LIQ", "LANASET BLUE 2R", "TERASIL BROWN W-VM", "TERASIL DARK BLUE W-VM",
    "TERASIL RED WW-3BSN", "TERASIL RUBINE W-VM", "TERASILTURQUOISE WXN", "FIXAPRET F-ECO LIQ"
]

added_count = 0
for name in product_names:
    obj, created = ProductMaster.objects.get_or_create(
        material_name=name,
        defaults={'material_code': name} # Use name as code if missing
    )
    if created:
        added_count += 1

print(f"Finished! Added {added_count} new products to Product Master.")
