# Generated by Django 6.0.3 on 2026-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('packsize', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('ship_to', models.TextField()),
                ('sold_to', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('packsize', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('ship_to', models.TextField()),
                ('sold_to', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(max_length=255)),
            ],
        ),
    ]
