# Generated by Django 6.0.3 on 2026-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=255)),
                ('avg_six_month_sales', models.FloatField(blank=True, null=True)),
                ('month_end_inventory', models.FloatField(blank=True, null=True)),
                ('mid_month_inventory', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
