# Generated by Django 6.0.3 on 2026-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_stocklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('product_bd_group', models.CharField(blank=True, max_length=100, null=True)),
                ('volumes', models.JSONField(default=dict)),
                ('total_volume', models.FloatField(blank=True, default=0, null=True)),
                ('values', models.JSONField(default=dict)),
                ('total_value', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
