# Generated by Django 6.0.3 on 2026-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_alter_order_customer_alter_order_invoice_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_order', models.CharField(blank=True, max_length=100, null=True)),
                ('so_creation_date', models.DateField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_to_party', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_to_party_address', models.TextField(blank=True, null=True)),
                ('ship_to_party', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('material_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('plant', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_per_unit', models.FloatField(blank=True, null=True)),
                ('billed_quantity', models.FloatField(blank=True, null=True)),
                ('assessable_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
