# Generated by Django 6.0.3 on 2026-04-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_primarysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalPriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('soldto_code', models.CharField(blank=True, max_length=100, null=True)),
                ('soldto_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipto_code', models.CharField(blank=True, max_length=100, null=True)),
                ('shipto_name', models.CharField(blank=True, max_length=255, null=True)),
                ('end_customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Sales Exec Review', 'Pending Sales Exec Review'), ('Pending Pricing & BD Teams', 'Pending Pricing & BD Teams'), ('Pending Sales Director', 'Pending Sales Director'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Sales Exec Review', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPRLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_proposal', models.CharField(blank=True, max_length=100, null=True)),
                ('price_request_type', models.CharField(blank=True, max_length=100, null=True)),
                ('material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('existing_dist_price', models.FloatField(blank=True, null=True)),
                ('existing_icp', models.FloatField(blank=True, null=True)),
                ('existing_sale_volume', models.FloatField(blank=True, null=True)),
                ('requested_dist_price', models.FloatField(blank=True, null=True)),
                ('requested_icp', models.FloatField(blank=True, null=True)),
                ('proposed_sale_volume', models.FloatField(blank=True, null=True)),
                ('freight_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('end_customer_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('product_used_in_package', models.CharField(blank=True, max_length=20, null=True)),
                ('other_products_details', models.CharField(blank=True, max_length=255, null=True)),
                ('competition_running', models.CharField(blank=True, max_length=20, null=True)),
                ('competition_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('competition_price', models.FloatField(blank=True, null=True)),
                ('competition_volume', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('epr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales_app.exceptionalpricerequest')),
            ],
        ),
    ]
