# Generated by Django 6.0.3 on 2026-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_exceptionalpricerequest_eprlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=255, unique=True)),
                ('column_mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
