# Generated by Django 6.0.3 on 2026-05-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0007_tradertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorinvoice',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
