# Generated by Django 6.0.3 on 2026-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_distributorinvoice_value_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
