# Generated by Django 6.0.3 on 2026-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0009_stocklevel_month_stocklevel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='end_customer_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='mat_div',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='pack_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='prod_hierracy_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='special_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
