# Generated by Django 6.0.3 on 2026-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0010_productmaster_end_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='organisation',
            field=models.CharField(blank=True, choices=[('inx1', 'inx1'), ('inx2', 'inx2')], max_length=10, null=True),
        ),
    ]
