# Generated by Django 6.0.3 on 2026-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0011_productmaster_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysales',
            name='billing_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='primarysales',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='primarysales',
            name='region_dlv_plant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primarysales',
            name='sales_order_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='primarysales',
            name='sales_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
