# Generated by Django 6.0.3 on 2026-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0012_primarysales_billing_item_primarysales_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysales',
            name='region_dlv_plant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='sales_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
