# Generated by Django on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0013_alter_primarysales_region_dlv_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysales',
            name='sales_exec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
