# Generated by Django on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0014_primarysales_sales_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysales',
            name='billing_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='region_dlv_plant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='sales_order_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarysales',
            name='sales_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
