# Generated by Django 6.0.3 on 2026-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0016_salesexecutivemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionalpricerequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Sales Exec Review', 'Pending Sales Exec Review'), ('Pending Pricing & BD Teams', 'Pending Pricing & BD Teams'), ('Pending Commercial Manager', 'Pending Commercial Manager'), ('Pending Sales Director', 'Pending Sales Director'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Sales Exec Review', max_length=50),
        ),
    ]
