# Generated by Django 6.0.3 on 2026-03-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sales_approved', 'Sales Approved'), ('csd_approved', 'CSD Approved'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('clarification', 'Clarification Requested')], default='pending', max_length=30)),
                ('distributor_code', models.CharField(blank=True, max_length=100)),
                ('legal_entity', models.CharField(blank=True, max_length=200)),
                ('territory', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(max_length=50)),
                ('approver_upn', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='onboarding.onboardingrequest')),
            ],
        ),
    ]
