# Generated by Django 6.0.3 on 2026-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sales_approved', 'Sales Approved'), ('csd_approved', 'CSD Approved'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('sent_back', 'Sent Back to Distributor'), ('clarification', 'Clarification Requested')], default='pending', max_length=30),
        ),
    ]
