# Generated by Django 6.0.3 on 2026-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_distributoruser_city_distributoruser_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoruser',
            name='organisation',
            field=models.CharField(blank=True, choices=[('inx1', 'inx1'), ('inx2', 'inx2')], max_length=10, null=True),
        ),
    ]
